version: "3.5"
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - '../:/var/www/html'
    container_name: python
    tty: true
    working_dir: '/var/www/html'
    links:
      - sqlserver
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: sqlserver
    hostname: sqlserver
    ports:
      - 1433:1433
    volumes:
      - ./sql:/sql
      - ./start-up.sh:/start-up.sh
      - mssql-db:/var/opt/mssql
    env_file:
      - common.env
    command: "sh -c '/start-up.sh & /opt/mssql/bin/sqlservr;'"
volumes:
  mssql-db:
    driver: local